[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=360000"
